---

- name: Manage Global Users in the test Environment
  hosts: chefservernode9withapache
  vars_files:
    - ./group_vars/all
  remote_user: '{{ user }}'
  gather_facts: True
  roles:
    - users

